version: "3.9"
services:
  ##if(UsePostgres)
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=testuser
      - POSTGRES_DB=test
  ##endif
  ##if(UseSqlServer)
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure-sql-edge
    ports:
      - "1433:1433"
    volumes:
      - sql_edge_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
  ##endif
  ##if(useMongo)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: veruecktemongo
    volumes:
      - mongodb_data:/data/db
    restart: always
  ##endif
  ##if(UseMySql)
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  ##endif
  ##if(useAzureTable)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: always
    ports:
      - "10002:10002" # Table service
    command: "azurite --loose --tableHost 0.0.0.0 --tablePort 10002 --location /workspace --debug /workspace/debug.log"
    volumes:
      - azurite_data:/workspace
  ##endif
volumes:
  ##if(UsePostgres)
  postgres_data:
  ##endif
  ##if(UseSqlServer)
  sql_edge_data:
  ##endif
  ##if(useMongo)
  mongodb_data:
    driver: local
  ##endif
  ##if(UseMysql)
  mysql_data:
  ##endif
  ##if(useAzureTable)
  azurite_data:
  ##endif
